# -*- coding: utf-8 -*-
"""Machine_Learning_Labs_BasictoAdvance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QN3hvRaH8-NFG8GIxhVfDfNXxHPrD90b
"""

# Important Machine Learning Lab Programs

import pandas as pd

data = {
    "Age": [22, 25, 47, 52, 46, 56, 55, 60, 62, 61, 18, 21, 23, 30, 35],
    "Salary": [25000, 30000, 60000, 80000, 75000, 90000, 85000, 95000, 100000, 98000, 20000, 22000, 28000, 40000, 50000],
    "Experience": [1, 2, 10, 15, 12, 20, 18, 25, 28, 24, 0, 1, 2, 5, 8],
    "Purchased": [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1]
}

df = pd.DataFrame(data)
df.head()

# Load Dataset Using Pandas

import pandas as pd
df = pd.DataFrame(data)
print(df)

# Print First 5 rows

df.head()

# Print Last 5 Rows

df.tail()

# Check Shape

df.shape

# Check Info

df.info()

# Check Describe

df.describe()

# Check Missing Values

df.isnull().sum()

# To cheeck missing value percentage

(df.isnull().sum() / len(df)) * 100

# To fill missing Values

df["Age"] = df["Age"].fillna(df["Age"].mean())

# Drop Missing rows:

df = df.dropna()

# Check Correlation

df.corr()

# Better View


import matplotlib.pyplot as plt

corr = df.corr()

plt.imshow(corr)
plt.colorbar()
plt.xticks(range(len(corr)), corr.columns)
plt.yticks(range(len(corr)), corr.columns)
plt.show()

"""+1 = strong positive relation
-1 = strong negative relation
0 = no relation
"""

# Use Train Test Split

from sklearn.model_selection import train_test_split

x = df[["Age","Experience"]]
y = df["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

print(x_train)
print(x_test)

# Train Linear Regression Model

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

x = df[["Age","Experience"]]
y = df["Salary"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LinearRegression()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

print("Predicted",y_pred)
print("Actual",y_test.values)

# Evaluate Linear Regression

from sklearn.metrics import mean_squared_error, r2_score

print("MAE:", mean_squared_error(y_pred,y_test))
print("MSE:", mean_squared_error(y_pred,y_test))
print("R2 Score:", r2_score(y_pred,y_test))

# Train Logistic Regression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

x = df[["Age","Salary","Experience"]]
y = df["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LogisticRegression()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

print("Predicted:", y_pred)
print("Actual:", y_test.values)

# Evaluate using Accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_pred,y_test)
print("Accuracy:", accuracy)

# Accuracy means:

# correct Prediction / Total Predictions

# Print Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_pred,y_test)

print("Confusion Matrix")
print(cm)

"""TN = actual 0, predicted 0
FP = actual 0, predicted 1
FN = actual 1, predicted 0
TP = actual 1, predicted 1
"""

# Classification matrix

from sklearn.metrics import classification_report

cr = classification_report(y_pred,y_test)

print("Classification Report")
print(cr)

# Train Decision Tree Model

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

x = df[["Age","Salary","Experience"]]
y = df["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = DecisionTreeClassifier(random_state=42)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

print("Prediction:", y_pred)

print("Accuracy:", accuracy_score(y_pred,y_test))
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

x = df[["Age", "Salary", "Experience"]]
y = df["Purchased"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=100, random_state=42)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Train Naive Bayes Model

# Train SVM model

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

x = df[["Age", "Salary", "Experience"]]
y = df["Purchased"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model = SVC(kernel="linear")

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

#. SVM tries to separate classes using a best boundary.

# Apply StandardScaler
"""
Scaling is importnat for:
KNN
SVM
K-Means
PCA

"""
from sklearn.preprocessing import StandardScaler

x = df[["Age","Salary","Experience"]]
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

print(x_scaled)

"""
mean = 0
standard Deviation = 1
"""

# Logistic Regression with StandardScaler

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

df = [["Age","Salary","Experience"]]
df = ["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(
                x,y,test_size= 0.2, random_state=42)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_scaled)

model = LogisticRegression()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

print("Accuracy:", accuracy_score(y_test,y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))

# fit_transform(): Use on Training data.
# transform(): Used on testing data
# Don not use fit_transform on test data

# Apply K-Means Clustering: K-Means is an unsupervised learning algorithm
# It does not need target column.

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

X = df[["Age", "Salary", "Experience"]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters

print(df)

# Plot K-Means Clusters


import matplotlib.pyplot as plt

plt.scatter(df["Age"], df["Salary"], c=df["Cluster"])
plt.xlabel("Age")
plt.ylabel("Salary")
plt.title("K-Means Clustering")
plt.show()

# Apply PCA: means Principal Component Analysis
# It is used for dimensionality reduction

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

x = df[["Age","Salary","Experience"]]

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

pca = PCA(n_components=2)
x_pca = pca.fit_transform(x_scaled)

print(x_pca)

# PCA Visualization

import matplotlib.pyplot as plt

plt.scatter(x_pca[:, 0], x_pca[:, 1], c=df["Purchased"])
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA Visualization")
plt.show()

# Use Cross-Validation: checks model performance on multiple splits

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

X = df[["Age", "Salary", "Experience"]]
y = df["Purchased"]

model = RandomForestClassifier(random_state=42)

scores = cross_val_score(model, X, y, cv=5)

print("Cross Validation Scores:", scores)
print("Average Accuracy:", scores.mean())

# Build Complete ML Pipeline

 from sklearn.pipeline import Pipeline
 from sklearn.preprocessing import StandardScaler
 from sklearn.ensemble import RandomForestClassifier
 from sklearn.model_selection import train_test_split
 from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
 import pandas as pd
 import numpy as np

 x = df[["Age","Salary","Experience"]]
 y = df["Purchased"]

 x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

 pipeline = Pipeline([
     ("scaler", StandardScaler()),
     ("model", RandomForestClassifier(random_state=42))
 ])

 pipeline.fit(x_train,y_train)

 y_pred = pipeline.predict(x_test)
 print("Accuracy_Score:", accuracy_score(y_test,y_pred))
 print("Confusion Matrix:")
 print(confusion_matrix(y_test,y_pred))
 print("Classification Report:")
 print(classification_report(y_test,y_pred))

 # Pipeline is useful because it prevents mistakes and keep code clean.

"""## **Complete** **Practice** **Code**"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data = {
    "Age": [22, 25, 47, 52, 46, 56, 55, 60, 62, 61, 18, 21, 23, 30, 35],
    "Salary": [25000, 30000, 60000, 80000, 75000, 90000, 85000, 95000, 100000, 98000, 20000, 22000, 28000, 40000, 50000],
    "Experience": [1, 2, 10, 15, 12, 20, 18, 25, 28, 24, 0, 1, 2, 5, 8],
    "Purchased": [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1]
}

df = pd.DataFrame(data)

# Basic EDA

print("First 5 Rows:")
df.head()

print("Last 5 Rows:")
df.tail()

print("Shape:")
df.shape

print("Info:")
df.info()

print("Describe:")
df.describe()

print("Missing Values:")
print(df.isnull().sum())

print("Correlation:")
print(df.corr())

# Regression: Linear Regression

x = df[["Age","Experience"]]
y = df["Salary"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LinearRegression()
model.fit(x_train,y_train)

y_pred_reg = model.predict(x_test)

print("\nLinear Regression Results:")
print("Predicted:", y_pred_reg)
print("Actual:", y_test.values)
print("MAE:", mean_absolute_error(y_test, y_pred_reg))
print("MSE:", mean_squared_error(y_test, y_pred_reg))
print("R2 Score:", r2_score(y_test, y_pred_reg))

# Classification Models

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

x = df[["Age", "Salary", "Experience"]]
y = df["Purchased"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=3),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(kernel="linear")
}

for name, model in models.items():
    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("model", model)
    ])

    pipeline.fit(x_train, y_train)
    y_pred = pipeline.predict(x_test)

    print("\nModel:", name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

# Cross Validation

rf_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", RandomForestClassifier(random_state=42))
])

scores = cross_val_score(rf_pipeline, x, y, cv=5)

print("Cross Validation Scores:")
print(scores)
print("Avearge Accuracy:", scores.mean())

# K-Means Clustering

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
df["Cluster"] = kmeans.fit_predict(x_scaled)

print("Data with Clusters:")
print(df)

plt.scatter(df["Age"], df["Salary"], c=df["Cluster"])
plt.xlabel("Age")
plt.ylabel("Salary")
plt.title("K-Means Clustering")
plt.show()

# PCA

pca = PCA(n_components=2)
x_pca = pca.fit_transform(x_scaled)

print("PCA Output")
print(x_pca)

plt.scatter(x_pca[:,0], x_pca[:,1], c=df["Purchased"])
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA Visualization")
plt.show()

